/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class me_mpg_Native */

#ifndef _Included_me_mpg_Native
#define _Included_me_mpg_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     me_mpg_Native
 * Method:    execute
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_me_mpg_Native_execute
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
